services:
  php:
    container_name: ${APP_PREFIX}-app
    image: supermariux/blnsphp:latest
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    restart: unless-stopped
    ports:
      - ${APP_SERVER_PORT:-9000}:9000
    networks:
      - backend
      - frontend
    volumes:
      - blnsphp:/var/www/html
      - ./app:/var/www/html
      - ./favicon.ico:/var/www/html/favicon.ico:cached
      - ./humans.txt:/var/www/html/humans.txt:cached
      - ./robots.txt:/var/www/html/robots.txt:cached
      - ./docker/php/:/usr/local/etc/php/conf.d/:ro
    environment:
      - TZ=Europe/London

  proxy:
    container_name: ${APP_PREFIX}-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT:-8088}:80
    tty: true
    depends_on:
      - php
    networks:
      - frontend
    volumes_from:
      - php
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
    environment:
      - NGINX_HOST=${APP_HOST:-blnsphp.local}
      - NGINX_PORT=80
      - TZ=Europe/London

volumes:
  blnsphp:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
